// 4-react-redux/3-eat-it-v3 ( async actions )/src/App.js


import React, { Component } from 'react';
import Navbar from './components/Navbar';
import ItemList from './components/ItemList'
import CartBadge from './components/CartBadge';
import CartView from './components/CartView';
import Home from './components/Home';
import NotFound from './components/NotFound';


import { BrowserRouter as Router, Route, Switch, Link } from 'react-router-dom';

class App extends Component {

  renderItems() {
    return <ItemList />
  }
  renderCart() {
    return <CartView />
  }
  handleItemsRoute(props) {
    let { type } = props.match.params
    if (type === 'food')
      return this.renderItems()
    else return (<div>Nil</div>)
  }
  render() {
    return (
      <div>
        <Navbar value={"Eat-IT"} />
        <hr />
        <CartBadge />
        <hr />
        <Router>
          <div>
            <ul className="nav nav-pills">
              <li className="nav-item">
                <Link className="nav-link" to="/">home</Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link" to="/items/food">food-items</Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link" to="/cart">cart</Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link" to="/orders">orders</Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link" to="/login">login</Link>
              </li>
            </ul>
            <hr />
            <div className="container">
              <Switch>
                <Route path="/" exact={true} component={Home} />
                <Route path="/items/:type" render={props => this.handleItemsRoute(props)} />
                <Route path="/cart" render={props => this.renderCart()} />
                <Route component={NotFound} />
              </Switch>
            </div>
          </div>
        </Router>
      </div>
    );
  }
}

export default App;

// 5-NG/5-eat-it-v5 ( routing ) /src/app/app.component.ts
import { Component } from '@angular/core';
import { ItemService } from './item.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {

}

<!-- As a link -->
<nav class="navbar navbar-light bg-info">
  <a class="navbar-brand" href="#">Eat-IT</a>
</nav>
<hr />
<app-cart-badge></app-cart-badge>
<hr />
<div class="container">

  <ul class="nav nav-pills">
    <li class="nav-item">
      <a class="nav-link" routerLink="/">home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" routerLink="/items">food-items</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" routerLink="/cart">cart</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" routerLink="/orders">orders</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" routerLink="/login">login</a>
    </li>
  </ul>

  <hr />

  <router-outlet></router-outlet>

</div>
