// 4-react-redux/1-eat-it-v1/src/components/CartBadge.js




/*
import React from 'react';
const CartBadge = (props) => {
    const { value } = props;
    return (
        <div>
            <i className="fa fa-shopping-cart"></i>
            &nbsp;<span className="badge badge-danger">{value}</span>
            item(s) in cart
        </div>
    );
};

export default CartBadge;
*/

import React, { Component } from 'react';
import store from '../store'

class CartBadge extends Component {
    state = {
        count: 0
    }
    componentDidMount() {
        store.subscribe(() => {
            let cart = store.getState().cart;
            this.setState({ count: Object.keys(cart).length });
        })
    }
    render() {
        return (
            <div>
                <div>
                    <i className="fa fa-shopping-cart"></i>
                    &nbsp;<span className="badge badge-danger">{this.state.count}</span>
                    item(s) in cart
                </div>
            </div>
        );
    }
}

export default CartBadge;

// 5-NG/3-eat-it-v3 ( http ) /src/app/cart-badge/cart-badge.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { CartService } from '../cart.service';

@Component({
  selector: 'app-cart-badge',
  templateUrl: './cart-badge.component.html',
  styleUrls: ['./cart-badge.component.scss']
})
export class CartBadgeComponent implements OnInit {

  count = 0

  constructor(private cartService: CartService) { }

  ngOnInit() {
    this.cartService.getCartStream()
      .subscribe((e: any) => {
        let { cart } = e;
        this.count = Object.keys(cart).length
      })
  }

}

<i class="fa fa-shopping-cart"></i>
<span class="badge badge-danger" [innerText]="count"></span>
&nbsp; item(s) in cart
