// 3-react/2-eat-it-v2 ( comp-arch )/src/App.js


import React, { Component } from 'react';
import Navbar from './components/Navbar';
import Item from './components/Item'
import CartBadge from './components/CartBadge';
import CartView from './components/CartView';

class App extends Component {
  state = {
    isCartOpen: false,
    cart: {},
    items: [
      {
        id: 1,
        name: 'Veg',
        price: 100.00,
        canBuy: true,
        imgPath: 'images/veg.png',
        description: 'veg is always yummy & healthy'
      },
      {
        id: 2,
        name: 'NonVeg',
        price: 80.00,
        canBuy: true,
        imgPath: 'images/non-veg.png',
        description: 'non-veg is yummy but not healthy'
      }
    ]
  }
  constructor(props) {
    super(props)
    console.log("App :: constructor()");
  }

  /*
  {
    id:{item,qty}
  }
  */

  toggleCartView(e) {
    e.preventDefault()
    const { isCartOpen } = this.state;
    this.setState({ isCartOpen: !isCartOpen });
  }

  addToCart(e) {
    let { item } = e;
    let { id } = item;
    let { cart } = this.state;
    let cartLine;
    if (cart[id]) {
      cartLine = cart[id]
      cartLine = { ...cartLine, qty: cartLine.qty + 1 }
    } else {
      cartLine = { item, qty: 1 }
    }
    cart = { ...cart, [id]: cartLine }
    this.setState({ cart });
  }

  renderItems() {
    const { items, cart, isCartOpen } = this.state;
    if (!isCartOpen)
      return items.map((item, idx) => {
        let cartLine = cart[item.id] || {}
        let { qty } = cartLine
        qty = qty || 0
        return (
          <div key={idx} className="list-group-item">
            <Item value={item} cartQty={qty} onBuy={e => this.addToCart(e)} />
          </div>
        )
      })
  }
  renderCart() {
    const { cart, isCartOpen } = this.state;
    if (isCartOpen)
      return <CartView value={cart} />
  }
  render() {
    console.log("App :: render()");
    const { cart, isCartOpen } = this.state;
    return (
      <div>
        <Navbar value={"Eat-IT"} />
        <hr />
        <CartBadge value={Object.keys(cart).length} />
        <hr />
        <ul className="nav nav-pills">
          <li className="nav-item">
            <a onClick={e => this.toggleCartView(e)} className="nav-link" href="/">{isCartOpen ? 'items' : 'cart'}</a>
          </li>
        </ul>
        <hr />
        <div className="container">
          {this.renderCart()}
          {this.renderItems()}
        </div>
      </div>
    );
  }
}

export default App;

// 5-NG/1-eat-it-v1/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  cart = {}
  items = [
    {
      id: 1,
      name: 'Veg',
      canBuy: true,
      imgPath: 'assets/veg.png',
      makeDate: Date.now(),
      price: 100.00,
      discount: 100.00,
      description: 'free'
    }
  ]

  getCartQty() {
    return Object.keys(this.cart).length;
  }

  addToCart(e) {
    let { item, qty } = e;
    let { id } = item;
    let cartLine = this.cart[id];
    if (cartLine) {
      cartLine = { ...cartLine, qty: cartLine.qty }
    } else {
      cartLine = { item, qty: 1 }
    }
    this.cart = { ...this.cart, [id]: cartLine }
  }


}

<!-- As a link -->
<nav class="navbar navbar-light bg-info">
  <a class="navbar-brand" href="#">Eat-IT</a>
</nav>
<hr />
<app-cart-badge [value]="getCartQty()"></app-cart-badge>
<hr />
<div class="container">
  <app-cart-view [value]="cart"></app-cart-view>
  <br />
  <div *ngFor="let item of items | slice:0:100;let idx=index" class="list-group-item">
    <app-item [value]="item" (buy)="addToCart($event)"></app-item>
  </div>
</div>
