// 5-NG/3-eat-it-v3 ( http ) /src/app/cart-badge/cart-badge.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { CartService } from '../cart.service';

@Component({
  selector: 'app-cart-badge',
  templateUrl: './cart-badge.component.html',
  styleUrls: ['./cart-badge.component.scss']
})
export class CartBadgeComponent implements OnInit {

  count = 0

  constructor(private cartService: CartService) { }

  ngOnInit() {
    this.cartService.getCartStream()
      .subscribe((e: any) => {
        let { cart } = e;
        this.count = Object.keys(cart).length
      })
  }

}

<i class="fa fa-shopping-cart"></i>
<span class="badge badge-danger" [innerText]="count"></span>
&nbsp; item(s) in cart

// 4-react-redux/2-eat-it-v2 ( HOC )/src/components/CartBadge.js


import React from 'react';
import { connect } from 'react-redux'
 
const CartBadge = (props) => {
    const { value } = props;
    return (
        <div>
            <i className="fa fa-shopping-cart"></i>
            &nbsp;<span className="badge badge-danger">{value}</span>
            item(s) in cart
        </div>
    );
};

const mapStateToProps = state => {
    return {
        value: Object.keys(state.cart).length
    }
}

export default connect(mapStateToProps)(CartBadge);
