// 5-NG/3-eat-it-v3 ( http ) /src/app/item/item.component.ts
import { Component, OnInit, Input, EventEmitter, Output } from '@angular/core';
import { ItemService } from '../item.service';
import { CartService } from '../cart.service';

@Component({
  selector: 'app-item',
  templateUrl: './item.component.html',
  styleUrls: ['./item.component.scss']
})
export class ItemComponent implements OnInit {

  @Input('value') item;
  @Output() buy = new EventEmitter()
  currentTab: number = 1
  reviews = []

  constructor(
    private cartService: CartService,
    private itemService: ItemService) { }

  ngOnInit() {
  }

  handleBuy(event) {
    this.cartService.addToCart({ item: this.item, qty: 1 })
  }

  changeTab(event, tabIndex) {
    event.preventDefault()
    this.currentTab = tabIndex
    if (this.currentTab === 3) {
      this.itemService.getReviews(this.item.id)
        .subscribe(reviews => {
          this.reviews = reviews
        })
    }
  }
  isTabSelected(tabIndex) {
    return this.currentTab === tabIndex

  }

}

<div class="row">
  <div class="col-3 com-sm-3 col-md-3">
    <img [src]="item.imgPath" [alt]="item.name" class="img-fluid" />
  </div>
  <div class="col-9 com-sm-9 col-md-9">
    <div>
      <h5>{{item.name|uppercase}} <small>{{item.makeDate|date:'dd-MMM hh:mm a'}}</small></h5>
      <h6>{{item.price | priceDiscount:item.discount | currency:item.currencyCode:'symbol'}}</h6>
      <button (click)="handleBuy($event)" *ngIf="item.canBuy" class="btn btn-sm btn-dark">buy</button>
    </div>
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a (click)="changeTab($event,1)" [class.active]="isTabSelected(1)" class="nav-link" href="/">Description</a>
      </li>
      <li class="nav-item">
        <a (click)="changeTab($event,2)" [ngClass]="{'nav-link':true,active:isTabSelected(2)}" href="/">Ingre..</a>
      </li>
      <li class="nav-item">
        <a (click)="changeTab($event,3)" [ngClass]="{'nav-link':true,active:isTabSelected(3)}" class="nav-link"
          href="/">Reviews</a>
      </li>
    </ul>
    <div *ngIf="isTabSelected(1)">{{item.description}}</div>
    <div *ngIf="isTabSelected(2)">Not yet</div>
    <div *ngIf="isTabSelected(3)">
      <div *ngFor="let review of reviews">
        <app-review [value]="review"></app-review>
      </div>
    </div>
  </div>

  <!-- <pre>{{item|json}}</pre> -->

// 4-react-redux/2-eat-it-v2 ( HOC )/src/components/Item.js
import React, { Component } from 'react';
import classNames from 'classnames';
import Review from './Review';
import ReviewForm from './ReviewForm_v2';

import { loadReviews, addNewReview } from '../actions/reviews'
import { buy } from '../actions/cart'
import { connect } from 'react-redux'

class Item extends Component {
    state = {
        currentTab: 1,
    }

    addNewReview(e) {
        let { review } = e;
        let { value: item, addNewReview } = this.props;
        let { id } = item;
        addNewReview(id, review)
    }
    handleBuy() {
        let { value: item, buy } = this.props;
        buy(item)
    }
    renderBuyBtn(item) {
        if (item.canBuy) {
            return (
                <button onClick={e => this.handleBuy()} className="btn btn-sm btn-dark">buy</button>
            )
        }
    }
    changeTab(e, tabIndex) {
        e.preventDefault()
        this.setState({ currentTab: tabIndex }, () => {
            if (tabIndex === 3) {
                let { value: item, loadReviews } = this.props;
                let { id } = item;
                loadReviews(id);
            }
        }) // async
    }
    renderReviews() {
        const { reviews } = this.props;
        return reviews.map((review, idx) => {
            return <Review value={review} key={idx} />
        })
    }
    renderTabPanel(item) {
        const { currentTab } = this.state;
        switch (currentTab) {
            case 1:
                return (
                    <div>{item.description}</div>
                );
            case 2:
                return (
                    <div>Not Yet</div>
                )
            case 3:
                return (
                    <div>
                        {this.renderReviews()}
                        <ReviewForm onSubmit={e => this.addNewReview(e)} />
                    </div>
                )
            default:
                return;
        }
    }
    render() {
        let { currentTab } = this.state
        const { value: item, qty } = this.props;
        return (
            <div>
                <div className="row">
                    <div className="col-3 col-sm-3 col-md-3">
                        <img src={`${item.imgPath}`} className="img-fluid" alt={item.name} />
                    </div>
                    <div className="col-9 col-sm-9 col-md-9">
                        <h5>{item.name}</h5>
                        <h6>&#8377;{item.price}.00</h6>
                        {this.renderBuyBtn(item)}
                        &nbsp;<span className="badge badge-warning">{qty}</span>
                        <ul className="nav nav-tabs">
                            <li className="nav-item">
                                <a onClick={e => this.changeTab(e, 1)} className={`nav-link ${currentTab === 1 ? 'active' : ''}`} href="/">Description</a>
                            </li>
                            <li className="nav-item">
                                <a onClick={e => this.changeTab(e, 2)} className={classNames('nav-link', { active: currentTab === 2 })} href="/">Ingre..</a>
                            </li>
                            <li className="nav-item">
                                <a onClick={e => this.changeTab(e, 3)} className={classNames('nav-link', { active: currentTab === 3 })} href="/">Reviews</a>
                            </li>
                        </ul>
                        {this.renderTabPanel(item)}
                    </div>
                </div>
            </div>
        );
    }
}


const mapStateToProps = (state, props) => {
    let { value: item } = props;
    let { id } = item;
    let cartLine = state.cart[id] || {}
    let { qty } = cartLine;
    qty = qty || 0
    return {
        reviews: state.reviews[id] || [],
        qty
    }
}
const mapDispatchToProps = { loadReviews, addNewReview, buy }

export default connect(mapStateToProps, mapDispatchToProps)(Item);
